Date: Tue, 27 Dec 2011 09:27:37 -0000
Received: from 69.172.154.110
From: Ronald <ronald@example.com>
Subject: Shoes and socks

Hello Asheesh,<br />
<br />
I came to your site via Slashdot's story about key collisions.<br />
<br />
When I saw this page, I had to read, it's something I am careful about (ethics of where I spend my money). <br />
<br />
1) Thanks for reminding me of local group Adbusters' shoes, I'd completely forgotten.<br />
<br />
2) On CBC's Dragons' Den a guy who makes shoes in Africa made a presentation.  They seem like quite nice shoes -- hopefully I'll get a pair one of these days. <br />
<br />
You may be interested in them yourself, so, as someone with <b>no affiliations</b> to them, I'll pass along the company:<br />
<br />
<br />
<a rel="nofollow" href="http://www.oliberte.com">Oliberté Shoes</a>:<br />
&lt;blockquote&gt;<br />
Why Made in Africa? This is Africa.<br />
<br />
So what’s with this whole Africa thing people ask us sometimes. It’s simple, Oliberté is about creating a better Africa, that people see differently. And we do it by creating premium shoes, made of the highest quality possible working with amazing people – all in Africa.<br />
&lt;/blockquote&gt;

Homepage: https://www.maow.net
